name: Deployment

on:
  push:
    branches:
      - master

    paths-ignore:
      - '**.md'
      - './.github/images'

  workflow_run:
    workflows: ["CI"]
    
    types:
      - completed

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Cache npm modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            !~/.npm/_logs
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-

      - name: Run npm install
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Generate the .env
        run: cp .env.example .env

      - name: Generate the app key
        run: php artisan key:generate

      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Cache Configurations
        run: php artisan config:cache

      - name: Cache Routes
        run: php artisan route:cache

      - name: Cache Views
        run: php artisan view:cache
      
      - name: Prepare public directory for deployment
        run: |
          mkdir -p public_html
          cp -R public/* public_html/

      - name: Modify public/index.php for external Laravel app path
        run: |
          sed -i 's@require __DIR__ . "/../vendor/autoload.php"@require __DIR__ . "/../../my-laravel-app/vendor/autoload.php"@' public_html/index.php
          sed -i 's@$app = require_once __DIR__ . "/../bootstrap/app.php";@app = require_once __DIR__ . "/../../my-laravel-app/bootstrap/app.php";@' public_html/index.php

      - name: Deploy Laravel app excluding public folder
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER_URL }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ 
          server-dir: /tryout/

      - name: Deploy public directory to public_html
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER_URL }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public_html 
          server-dir: /public_html/
